import mongoose from 'mongoose';
import { Order } from '../models/order.model.js';
import ApiError from '../utils/apiError.js';
import { HTTP_STATUS, ORDER_STATUS } from '../constants.js';
import { runInTransaction, withSession } from '../utils/transaction.js';

/**
 * Creates an order from user's cart with atomic transaction.
 * Validates cart, extracts store binding, creates order, and clears cart atomically.
 *
 * @param {string} userId - MongoDB ObjectId of the user
 * @returns {Promise<Object>} Object containing the created order
 * @returns {Object} return.order - The newly created order document
 * @throws {ApiError} If cart is empty, invalid, or not associated with a store
 */
export const createOrderFromCart = async (userId) => {
  return await runInTransaction(async (session) => {
    const { validateCartForCheckout, clearCart } =
      await import('./cart.service.js');
    const User = mongoose.model('User');

    // 1. Strict validation (Throws error if price changes or stock is missing)
    const cart = await validateCartForCheckout(userId, session);

    // 2. Fetch user with addresses for delivery snapshot
    const user = await withSession(
      User.findById(userId).select('addresses'),
      session
    );
    if (!user) {
      throw new ApiError(HTTP_STATUS.NOT_FOUND, 'User not found');
    }

    // Get default address or first address
    const userAddress =
      user.addresses.find((addr) => addr.isDefault) || user.addresses[0];
    if (!userAddress) {
      throw new ApiError(
        HTTP_STATUS.BAD_REQUEST,
        'No delivery address found. Please add an address.'
      );
    }

    // Validate coordinates for delivery
    if (!userAddress.coordinates || userAddress.coordinates.length !== 2) {
      throw new ApiError(
        HTTP_STATUS.BAD_REQUEST,
        'Delivery address is missing geolocation coordinates.'
      );
    }

    // 3. Calculate distance from store to delivery address using geospatial query
    const { DarkStore } = await import('../models/darkStore.model.js');

    // Calculate distance using MongoDB's $geoNear
    const [storeWithDistance] = await withSession(
      DarkStore.aggregate([
        {
          $geoNear: {
            near: {
              type: 'Point',
              coordinates: userAddress.coordinates,
            },
            distanceField: 'distance',
            spherical: true,
            key: 'location', // Explicitly specify the index key to avoid ambiguity
            query: { _id: cart.storeId },
          },
        },
      ]),
      session
    );

    // Validate aggregation result - store must exist
    if (!storeWithDistance) {
      throw new ApiError(HTTP_STATUS.NOT_FOUND, 'Store not found');
    }

    // Validate distance calculation succeeded
    if (typeof storeWithDistance.distance !== 'number') {
      throw new ApiError(
        HTTP_STATUS.INTERNAL_SERVER_ERROR,
        'Failed to calculate delivery distance'
      );
    }

    const distanceInKm = storeWithDistance.distance / 1000; // Convert meters to km

    // 4. Calculate financial breakdown
    const { calculateDeliveryFee } = await import('../utils/deliveryFee.js');
    const itemsPrice = cart.totalBill;
    const deliveryFee = calculateDeliveryFee(distanceInKm);
    const totalAmount = itemsPrice + deliveryFee;

    // 4. Prepare the order document (orderNumber auto-generated by pre-save hook)
    const order = new Order({
      user: userId,
      storeId: cart.storeId,
      deliveryAddress: {
        addressLine1: userAddress.addressLine1,
        city: userAddress.city,
        pincode: userAddress.pincode,
        location: {
          type: 'Point',
          coordinates: userAddress.coordinates,
        },
      },
      items: cart.items.map((item) => ({
        product: item.product._id,
        name: item.product.name,
        quantity: item.quantity,
        price: item.priceSnapshot,
        unit: item.product.unit,
        image: item.product.image,
      })),
      itemsPrice,
      deliveryFee,
      deliveryDistance: distanceInKm,
      totalAmount,
      status: ORDER_STATUS.PENDING_PAYMENT,
    });

    // 5. Save with session (orderNumber generated here)
    await order.save({ session });

    // 6. Atomic Clear
    await clearCart(userId, session);

    return { order };
  });
};

/**
 * Gets user's order history with pagination and metadata
 * @param {string} userId - ID of the user whose orders are being retrieved
 * @param {Object} query - The request query object containing page and limit
 * @returns {Promise<Object>} - Object containing the array of lean order documents and pagination metadata
 */
export const getOrderHistory = async (userId, query) => {
  // 1. Extract standardized pagination numbers using the utility
  const { getPaginationOptions, getPaginationMetadata } =
    await import('../utils/pagination.js');
  const { skip, limit, page } = getPaginationOptions(query);

  // 2. Fetch orders and count in parallel
  // using lean() is faster for read-only queries
  // Sorting uses the compound index: { user: 1, createdAt: -1 }
  const [orders, totalOrders] = await Promise.all([
    Order.find({ user: userId })
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean(),
    Order.countDocuments({ user: userId }),
  ]);

  // 4. Generate standardized metadata (hasNextPage, totalPages, etc.)
  const pagination = getPaginationMetadata(totalOrders, limit, page);

  return {
    orders,
    pagination,
  };
};

/**
 * Gets specific order details for a user with security verification
 * @param {string} orderId - The MongoDB ID of the order
 * @param {string} userId - The ID of the user requesting the details (Security Check)
 * @returns {Promise<Object>} - The lean order document
 */
export const getOrderDetails = async (orderId, userId) => {
  // 1. Database fetch with security filter

  // lean() for memory optimization (read-only)
  const order = await Order.findOne({
    _id: orderId,
    user: userId,
  }).lean();

  // 2. Handle non-existent or unauthorized access
  if (!order) {
    throw new ApiError(
      HTTP_STATUS.NOT_FOUND,
      'Order not found or unauthorized'
    );
  }

  return order;
};

/**
 * Confirms order payment safely using Atomic Transactions.
 * Ensures Idempotency (handling duplicate webhooks) and Stock Management.
 *
 * @param {string} orderId - The unique Object ID of the order.
 * @param {string} paymentIntentId - The Stripe Payment Intent ID for reference.
 * @returns {Promise<Object|null>} The updated order object or null if stock is insufficient.
 * @throws {Error} Throws if transaction fails, triggering a Stripe Retry.
 */
export const confirmOrderPayment = async (orderId, paymentIntentId) => {
  return await runInTransaction(async (session) => {
    // 1. Fetch Order with Session Lock
    const order = await withSession(Order.findById(orderId), session);
    if (!order) {
      throw new ApiError(HTTP_STATUS.NOT_FOUND, 'Order not found');
    }

    // 2. Idempotency & State Guard
    if (order.status !== ORDER_STATUS.PENDING_PAYMENT) {
      return order;
    }

    // 3. Atomic Stock Deduction from Store Inventory
    const { StoreInventory } =
      await import('../models/storeInventory.model.js');

    for (const item of order.items) {
      const result = await StoreInventory.findOneAndUpdate(
        {
          storeId: order.storeId,
          productId: item.product,
          stock: { $gte: item.quantity },
        },
        { $inc: { stock: -item.quantity } },
        { session, new: true }
      );

      if (!result) {
        console.error(
          `[STOCK_CRITIQUE] Order ${orderId} failed: Store ${order.storeId} has insufficient stock for product ${item.product}`
        );

        // For standalone instances, we can't truly "abort" mid-loop easily without a formal session,
        // so we rely on the manual status update for cleanup or just accept partial consistency locally.
        if (session && session.inTransaction()) {
          await session.abortTransaction();
        }

        // Mark as FAILED
        try {
          await Order.findByIdAndUpdate(orderId, {
            status: ORDER_STATUS.FAILED,
          });
        } catch (updateError) {
          console.error(
            `[CRITICAL] Failed to mark order ${orderId} as FAILED after stock error`,
            updateError
          );
        }

        return null;
      }
    }

    // 4. Rider Assignment
    const { findAvailableRider, assignRiderToOrder } =
      await import('./rider.service.js');
    const { calculateStaticETA } = await import('../utils/eta.js');

    const availableRider = await findAvailableRider(order.storeId);

    if (!availableRider) {
      console.warn(`[RIDER] No riders available for order ${orderId}`);
      order.status = ORDER_STATUS.CONFIRMED;
    } else {
      const eta = calculateStaticETA(order.deliveryDistance);
      await assignRiderToOrder(availableRider._id, orderId, session);

      order.assignedRider = availableRider._id;
      order.estimatedDeliveryTime = eta;
      order.status = ORDER_STATUS.OUT_FOR_DELIVERY;

      console.log(
        `[RIDER] Order ${orderId} assigned to rider ${availableRider._id} with ETA ${eta} minutes`
      );
    }

    // 5. Update payment intent and save
    order.paymentIntentId = paymentIntentId;

    await order.save({ session });

    return order;
  });
};

/**
 * Handles payment failure by updating order status to FAILED.
 *
 * @param {string} orderId - The unique Object ID of the order.
 * @returns {Promise<Object>} The updated order object.
 */
export const handlePaymentFailure = async (orderId) => {
  const order = await Order.findById(orderId);

  if (!order) {
    throw new ApiError(HTTP_STATUS.NOT_FOUND, 'Order not found');
  }

  // Idempotency / State Guard
  // Why: If the order was somehow already confirmed (race condition),
  // we must NOT overwrite it with FAILED. Success takes precedence.
  if (order.status === ORDER_STATUS.PENDING_PAYMENT) {
    order.status = ORDER_STATUS.FAILED;
    await order.save();
  } else {
    // Log helpful info for debugging race conditions
    console.warn(
      `[IDEMPOTENCY] Skipped failure update for Order ${orderId}: Current Status is ${order.status}`
    );
  }

  return order;
};
